[package]
name = "uci"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "net"] }
tower-http = { version = "0.6.7", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }
