[workspace]
members = ["server", "client"]
resolver = "2"

[workspace.package]
version = "15.0.0"
edition = "2021"
authors = ["Olympus Team"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
